### PR TITLE
chore(font): make group better distinguishable from tasks

### PR DESCRIPTION
**Pull request by nikku**
This slightly increases the height of a group to make it better distinguishable from tasks:

__Before__

image

__After__

image

__After (smaller group)__

image

__After (smaller group + CSS fix / center align)__

image

Is this a good change? 

I could get some feedback on this :wind_face:

### CODE REVIEW

**Comment by pinussilvestrus** [comment]
Really like this approach! Just some thoughts:

We had it this way in the first place but after a discussion with @philippfromme, we decided to adjust the height/width to the task-icon _because the difference to the pool-icon_ looked a little bit uncomfortable. We thought the different border stroke should be enough to distinguish from tasks.

From my perspective, I'm ok with both approaches. Any thoughts @philippfromme

**Comment by philippfromme** [comment]
As @pinussilvestrus mentioned I initially gave feedback that led to the group icon being the same size as the task icon. I don't mind changing it.

**Comment by barmac** [comment]
I like the second version more. It's also easier distinguishable from event sub process which usually has a shape similar to the previous icon version. Now I can clearly say that it's a group.

**Comment by pinussilvestrus** [comment]
Proposal: Leaving the icon as it is, testing it out in practice, and change afterward when users complain about it.

**Comment by nikku** [comment]
Final proposal and comparison:

image

What is your vote?

**Comment by philippfromme** [comment]
v4 🚀

**Comment by barmac** [comment]
v4

**Comment by pinussilvestrus** [comment]
v4 !

**Comment by philippfromme** [comment]
🔥

**Pull request merged**
